import './globals.css'
import "bootstrap/dist/css/bootstrap.min.css";
import { Gabarito } from 'next/font/google'
import Navbar from '../Components/Navbar/Navbar';

const inter = Gabarito({ subsets: ['latin'], weight: '400'})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={inter.className}>
      <Navbar/>
      <main>{children}</main>

    </body>
    </html>
  )
}

